feature/task-1
LindaH32/kentico-onboarding-cs pull request #2
Opened 2017-04-22 14:51 UTC by LindaH32

2017-04-25 07:11 UTC, Suzii requested changes
Thanks for the PR :) There are however many issues with the code, that I'd like you to have a look at and fix. It should not take long, since there are no big problems and with most of them can be automatically fixed by ReSharper ;)

Some general notes:
- Have you ReSharper installed? There are many code fix suggestions that are glowing like christmas tree when I open VS (e.g. `ItemsController:16`). Have a look at it and try to listen to ReSharper suggensions whenever there are any, it will make you better programmers :)
- Unused imports -> use ReSharper to remove unused usings across whole solution (if you not sure how, ask for an assistance)
- It is named `ItemsController` for a reason, therefore, it is already said it will be only dealing with `items` (once you fix the naming issue mentioned below in the inline comment). There is no need to specify `Item` suffix for methods, as it it more than clear what they accept/return. Moreover, when one has a simple API, such as yours, it is a good convention to name the actions (public methods of controller) with the name of HTTP method they are dealing with. So something like `AddItem()` is not a particularly well chosen name for a controller method. Rename it to `Post()` and you won't even need the `[HttpPost]` attribute above it.
- So you ticked the "Learn why async" bullet point in Jira, but I can't see any async methods in controller :P Once you convert to async, give all methods `*Async` suffix.
- Controller actions should accept an object to make it more extensible.
- Tests should check that correct status code is returned.
- Delete referrence to `Microsoft.VisualStudio.QualityTools.UnitTestFramework` since you should be using only NUnit framework for testing.

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api/App_Start/WebApiConfig.cs
> +               name: "DefaultApiV2",
You have not yet merged the first real pull request and you already need v2 of your API?

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/Comparers/ListItemComparer.cs
> +namespace TodoList.Api.Comparers
Wrong namespace, let resharper fix it for you.

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/Comparers/ListItemComparer.cs
> +            return (x.Id.CompareTo(y.Id) == 0) && (x.Text.CompareTo(y.Text) == 0);
Why `CompareTo()`??? Use equals instead.

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api/Controllers/ItemsController.cs
> +            return Ok("Item deleted");
Either return the deleted item or use `StatusCode(HttpStatusCode.NoContent)` instead.

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api/Models/ListItem.cs
> +        [Required]
Do not use the attribute validation. This is because you have only one model for database object and same one for the DTO.  Controller should do the validation that corresponds to your UI validation and database layer should have separate validation rules if necessary.

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api/Models/ListItem.cs
> +            return $"ID: {Id}, Text:{Text}";
Use lambda expression.

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/Comparers/ListItemComparer.cs
> +            return (x.Id.CompareTo(y.Id) == 0) && (x.Text.CompareTo(y.Text) == 0);
If ReSharper says you should use the overload with `StringComparison`, there is probably [a reason](https://msdn.microsoft.com/en-us/library/dd465121(v=vs.110).aspx) for that.

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/Comparers/ListItemComparer.cs
> +            return ((obj.Id != null ? obj.Id.GetHashCode() : 0) * 397) ^ (obj.Text != null ? obj.Text.GetHashCode() : 0);
Use null-coalescing operator as ReSharper suggests (Alt+Enter)

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/ItemsControllerTest.cs
> +            controller = new ItemsController();
ReSharper -> use object initializer.

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/ItemsControllerTest.cs
> +            ListItem expected = new ListItem("666", "zirafa");
Use var. Holds for all other obvious cases.

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api/Models/ListItem.cs
> +        public string Id { get; set; }
Use `Guid` type and read how to use it properly (it's a structure).

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/ItemsControllerTest.cs
> +            List<ListItem> expected = new List<ListItem>(new ListItem[]
Use object initializer instead of constuctor argument.

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/ItemsControllerTest.cs
> +            action.Result.TryGetContentValue(out actual);
Call `Result` already on line 39, that is the `action`, not the `Task` that you stored into the variable. Holds for all other tests below.

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api/Controllers/ItemsController.cs
> +            if (text == null)
Use `string.IsNullOrWhiteSpace(value)` instead. Do not forget to add a unit tests for that. Try parametrized test ([`[TestCase()]`](https://github.com/nunit/docs/wiki/TestCase-Attribute) attribute from NUnit.

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/ItemsControllerTest.cs
> +
Why empty lines?

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api/Controllers/ItemsController.cs
> +        // TODO change List to IEnumerable
Submitting PR with TODO comments just does not feel right.

2017-04-25 07:11 UTC, Suzii commented on KenticoListApp/TodoList.Api/Controllers/ItemsController.cs
> +    public class ItemsController : ApiController
It is called `ItemsController` although the model it is responsible for is called `ListItem`. Rename one of them to make it consistent!

2017-04-25 07:14 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/Comparers/ListItemComparer.cs
> +            return (x.Id.CompareTo(y.Id) == 0) && (x.Text.CompareTo(y.Text) == 0);
Have a look at [string coparison guidelines wiki page](https://kentico.atlassian.net/wiki/display/ARCH/String+Comparison+Guidelines)

2017-04-27 07:37 UTC, Suzii requested changes
This review was done by Tobias. You did a great job in fixing many problems. Unfortunately there are still some details that need to be fixed.

Create file structure in tests according to Guidelines (controllers test should be in Controllers/ folder)

Use ReSharper to remove unused imports. Unused imports in `Global.asax.cs` and `AssemblyInfo.cs` kind of convinced you, that you did it manually. If you do not know how to tell ReSharper to remove the imports across the solution, please ask.

2017-04-27 07:37 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/Comparers/ListItemComparer.cs
> +
Empty lines again?

2017-04-27 07:37 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/Comparers/ListItemComparer.cs
> +            return (x.Id.Equals(y.Id) && x.Text.Equals(y.Text));
Unnecessary parenthesis...listen to ReSharper! Same for below method.

2017-04-27 07:37 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/ListItemsControllerTest.cs
> +            var expected = new ListItem(new Guid("00000000-0000-0000-0000-000000000000"), "text");
You can use `Guid.Empty`.

2017-04-27 07:37 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/ListItemsControllerTest.cs
> +        public void Post_ItemWithNullText_IsOfCorrectStatusCode()
You can merge this with `Post_ItemWithNullText_ReturnsErrorMessage` as they are almost same.

2017-04-27 07:37 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/ListItemsControllerTest.cs
> +        public void Post_WithNullArguments_IsOfCorrectStatusCode()
You can merge this with `Post_WithNullArguments_ReturnsErrorMessage` as they are almost same. This applies to all other tests where you have same set-up and different assert.

2017-04-27 07:37 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/ListItemsControllerTest.cs
> +            var expectedListItem = new ListItem(new Guid("00000000-0000-0000-0000-000000000000"), "text");
Unify usage of `Guid.Empty`.

2017-04-27 07:37 UTC, Suzii commented on KenticoListApp/TodoList.Api.Tests/ListItemsControllerTest.cs
> +            var expectedListItem = new ListItem(new Guid("20000000-0000-0000-0000-000000000000"), "updated");
You can create constant `nonEmptyGuid` and re-use it.

2017-04-27 07:37 UTC, Suzii commented on KenticoListApp/TodoList.Api/Controllers/ListItemsController.cs
> +            new ListItem(new Guid("00000000-0000-0000-0000-000000000000"), "text"),
You should never return an item with empty Guid. You can go to Tools->Create Guid and create random Guid.

2017-04-27 07:37 UTC, Suzii commented on KenticoListApp/TodoList.Api/Controllers/ListItemsController.cs
> +            return Ok(await Task.FromResult(SampleItems[0]));
Should return Created (201) statusCode...read about status codes that REST methods should return. You can look [here](http://www.restapitutorial.com/httpstatuscodes.html) (those codes with stars) that are most widely used.

2017-04-27 07:37 UTC, Suzii commented on KenticoListApp/TodoList.Api/Models/ListItem.cs
> +        public ListItem(Guid id)
This one should call the other if you need it. Question is if you want to have special constructor just because of tests.

2017-04-27 07:37 UTC, Suzii commented on KenticoListApp/TodoList.Api/Models/ListItem.cs
> +        public override string ToString() => $"ID: {Id}, Text:{Text}";
Add new line before => to make it more readable.

2017-04-27 07:37 UTC, Suzii commented on KenticoListApp/TodoList.Api/Controllers/ListItemsController.cs
> +            if (item == null)
Add validation to new private method.

2017-04-27 07:37 UTC, Suzii commented on KenticoListApp/TodoList.Api/Controllers/ListItemsController.cs
> +        public async Task<IHttpActionResult> Post(ListItem item)
You should add *Async suffix as in other methods.

2017-05-03 07:16 UTC, tobiaskamenicky approved these changes
OK, you've done a good job and finally fixed all issues. 

There are just a few inline comments that you might remember in the next task. It is nice, that you finally used ReSharper to fix code issues but remember to not overuse it. Be sure what are you trying to accomplish as ReSharper might do more than what you asked for and break your solution... :D (i.e. renaming, deleting, removing redundancies, etc.)

2017-05-03 07:16 UTC, tobiaskamenicky commented on KenticoListApp/TodoList.Api/ApplicationInsights.config
>  ﻿<?xml version="1.0" encoding="utf-8"?>
Do not overuse ReSharper..there is no reason to format this file...You can always check what was changed or let ReSharper show you detected issues prior to refactoring. (You don't have to change, just so you know)

2017-05-03 07:16 UTC, tobiaskamenicky commented on KenticoListApp/TodoList.Api/Controllers/ListItemsController.cs
> +            if (item.Id != Guid.Empty)
If you don't expect the Id to be set, it is always better to compare with default(Guid) instead of Guid.Empty even though they are equal. With default keyword, you don't have to look for default value yourselves.

2017-05-03 07:16 UTC, tobiaskamenicky commented on KenticoListApp/TodoList.Api/Controllers/ListItemsController.cs
> +            return Created("api/v1/items/?id=300...", await Task.FromResult(SampleItems[0]));
Well...for now..., just remember to change this in the next tasks.

2017-05-03 07:23 UTC, sutrkiller commented on KenticoListApp/TodoList.Api/App_Start/WebApiConfig.cs
> +                "api/v1/{controller}/{id}",
You should also keep the value for default controller. Now you are exposing the project files and structure on default route...

2017-05-03 07:26 UTC, Suzii approved these changes

2017-05-03 07:26 UTC, merged